from .aki import Aki
from .amigoz import Amigoz
from .bmgCLT import BmgCLT
from .brb360 import Brb360
from .brbInconta import Brbinconta
from .brbred import BrbRed
from .btw import Btw
from .bv import Bv
from .c6auto import C6auto
from .c6bankcreditomanual import C6bankcreditomanual
from .c6bankcomissao import C6bankcomissao
from .c6bankdebitomanual import C6bankdebitomanual
from .c6kgiro import C6kgiro
from .c6equity import C6equity
from .caixa import Caixa
from .comissaozerada import ComissaoZerada
from .crefisa import Crefisa
from .digio import Digio
from .empresteicred import Empresteicred
from .euro import Euro
from .evol import Evol
from .facta import Facta
from .grandino import Grandino
from .happy import Happy
from .hope import Hope
from .icred import Icred
from .jbcred import Jbcred
from .kardbank import Kardbank
from .nbc import Nbc
from .neo import Neo
from .novosaque import Novosaque
from .novosaquecartao import Novosaquecartao
from .nyc import Nyc
from .paranabank import Paranabank
from .panLafy import PanLafy
from .phtech import Phtech
from .presenca import Presenca
from .qualibank import Qualibank
from .capitalconsigcancelados import CapitalConsigCancelados
from .capitalconsigcomissao import CapitalConsigComissao
from .capitalconsigseguro import CapitalConsigSeguro
from .safracomissaozero import Safracomissaozero
from .santanderfit import Santanderfit
from .santanderFve6 import Santanderfvevi
from .OLE_FVE import OLE_FVE
from .totalcash import Totalcash
from .v8 import V8
from .vctex import Vctex
from .viacerta import Viacerta
from .webcash import Webcash

bancos = {
    "aki": lambda df: Aki().run(df),
    "amigoz": lambda df: Amigoz().run(df),
    "bmgclt": lambda df: BmgCLT().run(df),
    "brb360": lambda df: Brb360().run(df),
    "brbinconta": lambda df: Brbinconta().run(df),
    "brbred": lambda df: BrbRed().run(df),
    "btw": lambda df: Btw().run(df),
    "bv": lambda df: Bv().run(df),
    "c6auto": lambda df: C6auto().run(df),
    "c6bankcreditomanual": lambda df: C6bankcreditomanual().run(df),
    "c6bankcomissao": lambda df: C6bankcomissao().run(df),
    "c6bankdebitomanual": lambda df: C6bankdebitomanual().run(df),
    "c6kgiro": lambda df: C6kgiro().run(df),
    "c6equity": lambda df: C6equity().run(df),
    "caixa": lambda df: Caixa().run(df),
    "comissaozerada": lambda df: ComissaoZerada().run(df),
    "crefisa": lambda df: Crefisa().run(df),
    "digio": lambda df: Digio().run(df),
    "empresteicred": lambda df: Empresteicred().run(df),
    "euro": lambda df: Euro().run(df),
    "evol": lambda df: Evol().run(df),
    "facta": lambda df: Facta().run(df),
    "grandino": lambda df: Grandino().run(df),
    "happy": lambda df: Happy().run(df),
    "hope": lambda df: Hope().run(df),
    "icred": lambda df: Icred().run(df),
    "jbcred": lambda df: Jbcred().run(df),
    "kardbank": lambda df: Kardbank().run(df),
    "nbc": lambda df: Nbc().run(df),
    "neo": lambda df: Neo().run(df),
    "novosaque": lambda df: Novosaque().run(df),
    "novosaquecartao": lambda df: Novosaquecartao().run(df),
    "nyc": lambda df: Nyc().run(df),
    "paranabank": lambda df: Paranabank().run(df),
    "panlafy": lambda df: PanLafy().run(df),
    "phtech": lambda df: Phtech().run(df),
    "presenca": lambda df: Presenca().run(df),
    "qualibank": lambda df: Qualibank().run(df),
    "capitalconsigcancelados": lambda df: CapitalConsigCancelados().run(df),
    "capitalconsigcomissao": lambda df: CapitalConsigComissao().run(df),
    "capitalconsigseguro": lambda df: CapitalConsigSeguro().run(df),
    "safracomissaozero": lambda df: Safracomissaozero().run(df),
    "santanderfit": lambda df: Santanderfit().run(df),
    "santanderfvevi": lambda df: Santanderfvevi().run(df),
    "ole_fve": lambda df: OLE_FVE().run(df),
    "totalcash": lambda df: Totalcash().run(df),
    "v8": lambda df: V8().run(df),
    "vctex": lambda df: Vctex().run(df),
    "viacerta": lambda df: Viacerta().run(df),
    "webcash": lambda df: Webcash().run(df)
}